import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rasseta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          
          {children}
          
        </div>       
        </body>
    </html>
  );
}
