import type { Metadata } from "next";
import { Inter } from "next/font/google";


import Home from "./page";
import Homes from "./page";



import LandingPage from "@/components/landingPage/LandingPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rasseta Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          
          {children}
         
        </div>       
        </body>
    </html>
  );
}
